apiVersion: "v1"
kind: "Service"
metadata:
  name: "hello-app"
  labels:
    app: "hello-app"
spec:
  ports:
  - protocol: "TCP"
    port: 8081
    targetPort: 8080
  selector:
    app: "hello-app"
  type: "LoadBalancer"
